### ISSUE TITLE
[Bug Report] all jack-o-lanterns are facing north

### ISSUE THREAD

**Issue by KarBoy2314PL** [Domi04151309/NaturalFaithful#12]
**Description**

a bit of an oversight on my part, i see you did update carved pumpkins, but i overlooked jack-o-lanterns, they have a similar problem

<details>
  <summary><b>Screenshots</b></summary>

![2020-03-30_13 08 37](https://user-images.githubusercontent.com/8020330/77906146-c0432a00-7287-11ea-93a9-cfc51c26c197.png)

</details>

<details>

**Additional information**

 - Minecraft version: 1.15.2
 - Other packs used: -

**Comment by Domi04151309** [comment]
Oh, I forgot about them. They should be fixed now as well.
