### ISSUE TITLE
[Bug Report] Mossy Stone Brick Slab uses brick texture

### ISSUE THREAD

**Issue by Aegarain** [Domi04151309/NaturalFaithful#27]
The third model for the mossy stone brick slab uses the clay brick texture instead of the mossy stone texture.

https://github.com/Domi04151309/NaturalFaithful/blob/master/assets/minecraft/models/block/mossy_stone_brick_slab/3.json

**Comment by h3oCharles** [comment]
confirmed

![2020-10-30_11 33 30](https://user-images.githubusercontent.com/8020330/97695071-c3afc580-1aa3-11eb-9687-867acfc7bbed.png)

**Comment by h3oCharles** [comment]
replace "bricks3" to "mossy_stone_bricks3", pull request coming in
