### ISSUE TITLE
[Bug Report] Glowing effects

### ISSUE THREAD

**Issue by CelestialBlade** [Domi04151309/NaturalFaithful#5]
The glowing effect on items such Potions and the End Crystal is yellow, No color can be seen
( of the potions ). 
Please fix this - I love this pack!
Thank you for the pack!

**Comment by untuned** [comment]
The glint is too bright, even mobs with enchanted armor show in complete darkness.

**Comment by Domi04151309** [comment]
It should be a little bit less bright and less extreme now.

**Comment by CelestialBlade** [comment]
It is still very strong yellow. May I ask when you made the choice to strengthen the effect?
The normal Glowy Enchanting one is fine .

**Comment by Domi04151309** [comment]
The effect seems strengthened because yellow is a brighter color than purple but theoretically it is the original texture with changed hue.

**Comment by CelestialBlade** [comment]
So you only changed the hue? What was the problem with the original one?
Just asking

**Comment by Domi04151309** [comment]
There really wasn't a problem with the original one. I just prefer a golden glint over a purple one.

**Comment by CelestialBlade** [comment]
OHH. ok. How did you change it? I want to alter it too for myself If I can. 
Also another side note - the Real Nature Resource Pack is way too old.
The dev stopped supporting it - may I suggest Dramatic Skies instead?
Looking better Imo. https://www.curseforge.com/minecraft/texture-packs/dramatic-skys

**Comment by Domi04151309** [comment]
If you're on Windows you can use [Paint.net](https://www.getpaint.net/) to change [this file](https://github.com/Domi04151309/NaturalFaithful/blob/master/assets/minecraft/textures/misc/enchanted_item_glint.png).

I can't use Dramatic Skies because it's copyrighted. Real Nature's license makes it possible to use parts of the pack.
